-- Banco de dados de exemplo para testar a aplicação
-- Nome do banco usado em connection/conectar.php: info3a2023

DROP DATABASE IF EXISTS `info3a2023`;
CREATE DATABASE `info3a2023` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `info3a2023`;

-- Tabela de usuários (ordem de colunas alinhada com o uso nos PHPs)
CREATE TABLE `USUARIO` (
  `EMAIL_USUARIO` VARCHAR(255) NOT NULL PRIMARY KEY,
  `NOME` VARCHAR(255) NOT NULL,
  `DATANASCIMENTO` DATE DEFAULT NULL,
  `TELEFONE` VARCHAR(50) DEFAULT NULL,
  `ENDERECO` VARCHAR(255) DEFAULT NULL,
  `BAIRRO` VARCHAR(255) DEFAULT NULL,
  `CIDADE` VARCHAR(255) DEFAULT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `COMPLEMENTO` VARCHAR(255) DEFAULT NULL,
  `CEP` VARCHAR(50) DEFAULT NULL,
  `BLOQUEADO` TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de autores
CREATE TABLE `AUTOR` (
  `ID_AUTOR` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `NICKNAME` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tipos de obra
CREATE TABLE `TIPO_OBRA` (
  `ID_TIPOOBRA` INT NOT NULL PRIMARY KEY,
  `DESCRICAO` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Obras
CREATE TABLE `OBRA` (
  `ID_OBRA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DESCRICAO` VARCHAR(255) NOT NULL,
  `FOTO` VARCHAR(500) DEFAULT NULL,
  `DATA_REQUERIDA` DATE DEFAULT NULL,
  `DATA_CRIACAO` DATE DEFAULT NULL,
  `ID_TIPOOBRA` INT DEFAULT NULL,
  `ID_AUTOR` INT DEFAULT NULL,
  FOREIGN KEY (`ID_TIPOOBRA`) REFERENCES `TIPO_OBRA`(`ID_TIPOOBRA`),
  FOREIGN KEY (`ID_AUTOR`) REFERENCES `AUTOR`(`ID_AUTOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Favoritos (ligação entre usuário e obra)
CREATE TABLE `FAVORITO` (
  `FK_USUARIO` VARCHAR(255) NOT NULL,
  `FK_OBRA` INT NOT NULL,
  PRIMARY KEY (`FK_USUARIO`, `FK_OBRA`),
  FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO`(`EMAIL_USUARIO`) ON DELETE CASCADE,
  FOREIGN KEY (`FK_OBRA`) REFERENCES `OBRA`(`ID_OBRA`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dados de exemplo
INSERT INTO `TIPO_OBRA` (`ID_TIPOOBRA`, `DESCRICAO`) VALUES
(1,'Pintura'),(2,'Escultura'),(3,'Desenho'),(4,'Fotografia');

INSERT INTO `USUARIO` (`EMAIL_USUARIO`,`NOME`,`DATANASCIMENTO`,`TELEFONE`,`ENDERECO`,`BAIRRO`,`CIDADE`,`SENHA`,`COMPLEMENTO`,`CEP`,`BLOQUEADO`) VALUES
('admin','Administrador',NULL,'','','','','12345',NULL,NULL,0),
('user@example.com','Usuário Teste','1990-01-01','11999999999','Rua Exemplo, 123','Bairro Exemplo','Cidade Exemplo','senha',NULL,'00000-000',0);

INSERT INTO `AUTOR` (`NOME`,`EMAIL`,`NICKNAME`) VALUES
('Autor Exemplo','autor@example.com','autor1');

-- Inserções de exemplo apontando para imagens locais em /images
INSERT INTO `OBRA` (`DESCRICAO`,`FOTO`,`DATA_REQUERIDA`,`DATA_CRIACAO`,`ID_TIPOOBRA`,`ID_AUTOR`) VALUES
('Obra Teste 1','images/img-3.png','2025-12-31','2020-01-01',1,1),
('Obra Teste 2','images/img-4.png','2025-11-30','2019-05-20',2,1),
('Obra Teste 3','images/img-5.png','2026-01-15','2018-07-10',3,1),
('Obra Teste 4','images/img-6.png',NULL,'2021-02-02',4,1);

INSERT INTO `FAVORITO` (`FK_USUARIO`,`FK_OBRA`) VALUES
('user@example.com',1);

-- Fim do script
